workforce-data-initiative/skills-ml

README.md

Fixes https://github.com/workforce-data-initiative/skills-ml/issues/4
I wanted to get a simple README in here. I specifically didn't try and document specific algorithm implementations here in the repo, mainly because we should do that in a more deliberate way (some mixture of Sphinx reading autodocs from the modules, and having documents in the wiki). That should probably a separate task than the basic instructions for using the repository, which is all I tried to do here.

Update README to the current state of the repo

---

.gitignore
dags/simple_machine_learning.py
example_config.yaml
utils/s3.py

A quick change to add a local mode configuration option, which doesn't upload the results to S3. This makes some development tasks easier.

Implement local mode

---

algorithms/skill_importance_extractors/onet.py
dags/simple_machine_learning.py
tests/test_skill_importance_extractors.py

I think this is the one part missing from what's necessary to produce tables that go into the skills api database, all in skills-ml. From what I could tell, that process was really just concatenating all the KSAs together without any real processing.

Skill Importance Extraction

---

algorithms/aggregators/title.py
algorithms/job_geography_queriers/cbsa.py
dags/geo_title_counts.py
datasets/__init__.py
datasets/cousub_ua.py
datasets/nber_county_cbsa.py
datasets/place_ua.py
datasets/ua_cbsa.py
requirements.txt
tests/test_datasets_cousub_ua.py
tests/test_datasets_nber_county_cbsa.py
tests/test_datasets_place_ua.py
tests/test_datasets_ua_cbsa.py
tests/test_job_geo_queriers.py
tests/test_title_aggregators.py

- Replace county->CBSA lookup with UA->CBSA lookup
- Add GeoTitleAggregator class to count cleaned titles per geography
- Add GeoTitleCounts DAG to create counts of cleaned titles for both geo and overall.

Geography Title Counting

---

skills_ml/datasets/raw_job_postings/virginia.py
tests/test_datasets_raw_job_postings_virginia.py

- Switch from .iteritems to cross-version .items
- Add VA transformer test

Add python3 compatibility to VA transformer, add test [Resolves #50]

---

skills_ml/datasets/partner_updaters/__init__.py
skills_ml/datasets/partner_updaters/usa_jobs.py
tests/test_datasets_partner_updaters_usajobs.py

- Create datasets.partner_updaters.usa_jobs module for nightly USAJobs sync

USAJobs sync [Resolves #53]

---

skills_ml/datasets/raw_job_postings/__init__.py
skills_ml/datasets/raw_job_postings/usajobs.py
tests/test_datasets_raw_job_postings_usajobs.py

- Add USAJobs Common Schema ETL
- Add test for USAJobs ETL

USAJobs Common Schema ETL [Resolves #55]

---

requirements_dev.txt
skills_ml/algorithms/aggregators/dataset_transform.py
tests/test_transform_dataset_stats.py

- Add stats counter for quarterly datasets which counts occurrences of data fields, pre and post transform, for a given quarter in a dataset
- Add aggregators for all quarters within a dataset, and all datasets

Dataset Stats Generation [Resolves #61]

---

skills_ml/algorithms/occupation_classifiers/classifiers.py
tests/test_occupation_classifiers.py

This PR is mainly just a new module occupation_classifiers in algorithms. Now it has only one class SocClassifier() which is a SOC code classifier implemented by gensim.

Occupation classifier

---

skills_ml/algorithms/occupation_classifiers/classifiers.py
tests/test_occupation_classifiers.py

Now the classify() outputs a tuple of predicted soc code and the score(cosine similarity).

Similarity score

---

skills_ml/algorithms/aggregators/__init__.py
skills_ml/algorithms/aggregators/title.py
skills_ml/algorithms/jobtitle_cleaner/clean.py
skills_ml/algorithms/occupation_classifiers/classifiers.py
tests/test_occupation_classifiers.py
tests/test_title_aggregators.py

- Add SocCodeAggregator subclass that takes in an occupation classifier and calls classify for a given job posting

Create SOC code aggregator [Resolves #67]

---

skills_ml/algorithms/aggregators/geo.py
skills_ml/algorithms/aggregators/soc_code.py
skills_ml/algorithms/aggregators/title.py
tests/test_soc_aggregators.py

- Refactor GeoTitleAggregator into a GeoAggregator base class and minimal title subclass
- Create GeoSocAggregator as new subclass of GeoAggregator for SOC code counting

Add GeoSocAggregator [Resolves #71]

---

skills_ml/algorithms/aggregators/__init__.py
skills_ml/datasets/job_postings.py
tests/test_title_aggregators.py

- Pad CSV output counts with empty strings to ensure CSV shape
- Fix output header for total # of occurrences
- Add highmem job postings reader that doesn't use disk

Fixes from production

---

skills_ml/algorithms/aggregators/__init__.py
skills_ml/algorithms/aggregators/soc_code.py
tests/test_soc_aggregators.py
tests/test_title_aggregators.py

- Allow the absence of a classifier in the GeoSocAggregator, use given SOC code if so
- Create GivenSOCAggregator subclass of JobAggregator to allow 'top n given SOC codes' in any aggregator

Aggregate based on given SOC code [Resolves #74]

---

requirements.txt
skills_ml/algorithms/occupation_classifiers/classifiers.py
tests/test_occupation_classifiers.py

- Updated gensim to latest 2.2.0 version.
- Fixed docstrings in classifiers.py

Gensim updated

---

skills_ml/algorithms/job_geography_queriers/cbsa.py
skills_ml/algorithms/occupation_classifiers/classifiers.py

- Allow download of Annoy files into one place before any classifiers get loaded
- Fix CBSA hits list; sometimes tuple and sometimes list, can't figure out why, but converting to list regardless just works

Aggregator fixes

---

requirements.txt
skills_ml/datasets/__init__.py
skills_ml/datasets/job_postings.py
tests/test_datasets_job_postings.py

Don't get too excited at the branch name; I think a more comprehensive fix for this will be easier with boto3, and I tried to do this at first, but I soon found that doing the upgrade here will require more changes up the stack, so I have made a more basic bugfix here. (the upgrade should be its own task, not coupled with any functionality changes)
- Add retrying library to requirements
- Add test for job postings functions (we didn't have one before!) and that they retry
- Implement Retrying object with exponential backoff for job postings functions

Retry job_postings key download [Resolves #82]

---

skills_ml/algorithms/aggregators/dataset_transform.py
tests/test_transform_dataset_stats.py

- Add GlobalStatsAggregator.saved_total to retrieve the total # of job postings
- Add DatasetStatsAggregator.partner_list static method to retrieve a flat list of partners
- Add DatasetStatsCounter.quarterly_posting_stats static method to retrieve quarterly counts across partner

Enable easy dataset stats retrieval [Resolves #80]

---

requirements.txt
skills_ml/algorithms/occupation_classifiers/classifiers.py
skills_ml/datasets/cbsa_shapefile.py

- Require filelock module
- Use filelocking for both ann index download and CBSA shapefile download

Implement File locking [Resolves #93]

---

skills_ml/job_postings/common_schema.py
skills_ml/job_postings/computed_properties/computers.py
skills_ml/job_postings/corpora/basic.py
skills_ml/job_postings/geography_queriers/__init__.py
skills_ml/job_postings/geography_queriers/cbsa_from_geocode.py
tests/job_postings/test_common_schema.py
tests/job_postings/test_corpus_base.py
tests/job_postings/test_corpus_doc2vec_creator.py
tests/job_postings/test_corpus_word2vec_creator.py
tests/job_postings/test_job_geo_queriers.py

- Change all job posting generators from JSON string to dictionary, and change corpus creators to handle this

Convert JobPostingCollections from JSON string to dict

---

docs/sources/ontologies.md
requirements.txt
skills_ml/algorithms/occupation_classifiers/__init__.py
skills_ml/algorithms/occupation_classifiers/train.py
skills_ml/ontologies/onet.py
tests/algorithms/test_train_occupation_classifiers.py
tests/ontologies/test_onet.py

- Now the `build_onet()` function is executed in the Onet constructor. 
- Two new `cached properties `all_soc` and `all_major_group`

Onet ontology class

---

skills_ml/algorithms/embedding/models.py
tests/algorithms/test_embedding_models.py

Return a random array with the same size of vector when all of the words in the doc are unseen.

handle doc that has only unseen words

---

skills_ml/algorithms/skill_extractors/soc_exact.py

It would be nice to instantiate the SOC-Scoped Exact Match skill extractor without generating all the sub-ontologies upfront. It takes a while and you sometimes instantiate the object without needing all of them.
This change lazily creates sub-ontologies when needed

Lazy subontology

---

examples/SkillExtractionEvaluation.py
skills_ml/algorithms/skill_extractors/__init__.py
skills_ml/algorithms/skill_extractors/base.py
skills_ml/algorithms/skill_extractors/section_extract.py
skills_ml/algorithms/string_cleaners/nlp.py
skills_ml/job_postings/corpora/__init__.py
tests/algorithms/skill_extractors/test_section_extract.py
tests/algorithms/test_string_cleaners.py
tests/job_postings/test_corpus_section_creator.py

Introduces section extraction, which is aimed at zooming in on specific
sections of large pieces of unstructured text. It does this through
sentence/line/bullet heuristics. It comes in three flavors:
- basic utility function
- Word2Vec corpus creator that uses the utility function
- skill extractor that uses the utility function and assumes that each
sentence contained in the section is a distinct skill
The skill extractor is added to the skill extractor metric example,
along with some retooling so that non-list-based skill extractors make
more sense in that example.

Extract Section Text [Resolves #216]

---

skills_ml/ontologies/base.py
tests/ontologies/test_base.py

- Add logic to add_competency and add_occupation to update children and
parents of matching node if it exists

Update parents/children of existing Ontology nodes on merge [Resolves
