workforce-data-initiative/skills-ml

algorithms/elasticsearch_indexers/base.py
algorithms/elasticsearch_indexers/job_titles_master.py
algorithms/elasticsearch_indexers/normalize_topn.py
config.py
dags/index_job_titles_master.py
dags/normalize_elasticsearch.py
datasets.py
requirements.txt
tests/test_es_indexers.py
utils/es.py

Porting the existing Elasticsearch normalizer to use the common schema. I took the opportunity to abstract some of the utilities I had already written in the old version, to remove some boilerplate when indexing things.
I kept these as separate DAGs because indexing the job title list only really happens once, or whenever we recompute the job titles master table. The normalization indexing step itself is based on job postings, and so it makes sense quarterly. This means it doesn't make sense to put them in the same DAG.
I think there is a DAG reorganization coming in general, as parts of the simple_machine_learning DAG belong with parts of this. But in adding all this code I didn't want to mix too much of that code in, to make this easier to read.

Normalize indexing

---

algorithms/job_normalizers/esa_jobtitle_normalizer.py
datasets.py
tests/test_esa_job_normalizer.py
tests/utils.py

I split the ESA Job Normalizer into two different parts to make it more easily testable: 
- The ONET Occupation grabber was moved to datasets.py. It's abstracted a little bit, and I can see us using it for other things.
- The normalizer itself, which now doesn't have any downloading code.
The latter part is what I'm more interested in testing. When controlling the ONET occupation list to a handful of occupations, it was easy to see what concepts were being extracted from the descriptions, and I just made up a job title that matched one of them well.

Test ESA Job Normalizer

---

dags/geo_title_counts.py
tests/test_utils_nlp.py
utils/nlp.py

In first pass title cleaning,
- strip apostrophes
- replace other punctuation with space
- Squash whitespace blocks down to one space
- PEP8 cleaned rest of utils.nlp

Fix job title first pass cleaning [Resolves #26]

---

algorithms/skill_extractors/onet_ksas.py
api_sync/v1/alembic.ini
api_sync/v1/alembic/README
api_sync/v1/alembic/env.py
api_sync/v1/alembic/script.py.mako
api_sync/v1/alembic/versions/d523e7e45456_added_ksa_type.py
api_sync/v1/models/skills_master.py
api_sync/v1/skills_master.py
requirements.txt
tests/api_sync/v1/input/skills_master_table.tsv
tests/api_sync/v1/test_skills_importance.py
tests/api_sync/v1/test_skills_master.py
tests/test_skill_extractors.py
utils/db.py

- Add alembic to repo to track schema migrations
- Abstract sqlalchemy connection url so it is available to Alembic config
- Add ksa_type to SkillMaster model, and create migration to add column
- Remove SkillMaster constructor so we can just use kwargs
- Populate ksa_type column in onet_ksa SkillExtractors CSV output
- Populate ksa_type column in skills_master_loader

Add ONET KSA distinctions to skills_master [Resolves #30]

---

dags/geo_title_counts.py
tests/test_utils_fs.py
utils/fs.py

Basically this PR is to put each type of geo_title_count or title_count into their own folders to make our S3 more organized. 
I'm doing the job_title_sampler now, and will PR another branch after this PR get merged.

Make the S3 /skills-public/pipeline/tables cleaner again

---

requirements_dev.txt
skills_ml/algorithms/aggregators/title.py
skills_ml/algorithms/job_geography_queriers/cbsa.py
skills_ml/datasets/ua_cbsa.py
tests/test_datasets_ua_cbsa.py
tests/test_job_geo_queriers.py
tests/test_title_aggregators.py

- Add CBSA name along with FIPS to Urbanized Area Crosswalk, Job Geography Querier, and Title Aggregator

Include CBSA Name and State in aggregations [Resolves #59]

---

skills_ml/algorithms/README.md
skills_ml/algorithms/aggregators/__init__.py
skills_ml/algorithms/aggregators/title.py
skills_ml/algorithms/corpus_creators/basic.py
skills_ml/algorithms/job_geography_queriers/cbsa.py
skills_ml/algorithms/skill_extractors/freetext.py
tests/test_skill_extractors.py
tests/test_title_aggregators.py

There are a few changes in here worth calling out that I'm not sure about. Suggestions welcome.
1. Given that we are adding more and more things into the title aggregation (this isn't the last thing we'll put in here!), I decided that positional return values just aren't going to cut it anymore.  So I introduced the `Aggregation`, which is for presenting the same data at different rollup levels. Right now it's `.by_geo` and `.rollup`, but I can see this getting broken up into `.by_cbsa`, `.by_state`, etc in the future. 
I also introduced `AllAggregations`, a container for multiple `Aggregation` you would want to access. So in here there are currently counts and skills, but soon we'll put in SOC codes, etc. The Aggregator just returns one of the `AllAggregations` objects, and the caller …

Extract and Aggregate Skills from Job Postings [Resolves #63]

---

skills_ml/algorithms/job_geography_queriers/cbsa.py
tests/test_job_geo_queriers.py

- Modify code and test for CBSA Job Querier to expect lists, not tuples

JobGeographyQuerier expects lists, not tuples

---

skills_ml/algorithms/aggregators/__init__.py
skills_ml/algorithms/aggregators/geo.py
tests/test_aggregators.py
tests/test_title_aggregators.py

- Implement in-place addition for JobAggregator to add two similar JobAggregators (populated from different slices of job postings in different processes) together
- Implement merge_job_aggregators method for GeoAggregator to merge a collection of job aggregators (also populated in different processes) together
- Add test case for new merge functions but also another to make sure that all of it is multiprocessing-ready (specifically, that everything that needs to be able to pickle across the process boundary does so)
- PEP8-fix test_title_aggregators.py

Support multiprocessing for aggregators [Resolves #77]

---

skills_ml/algorithms/geocoders/__init__.py
tests/test_geocoders.py
tests/test_job_geo_queriers.py

- Convert state code to name if possible when geocoding
- Update all tests that expected geocode strings to use code

Use state name instead of code for geocoding [Resolves #88]

---

skills_ml/algorithms/corpus_creators/basic.py
skills_ml/algorithms/occupation_classifiers/base.py
skills_ml/algorithms/occupation_classifiers/train.py
skills_ml/datasets/job_postings.py
tests/test_corpus_base.py
tests/test_corpus_word2vec_creator.py
tests/test_train_occupation_classifiers.py

Implemented the training part of doc2vec which will take a list of quarters and train a gensim doc2vec model. It will save the model, lookup table and model metadata to S3.
- Change some corpus creators to match doc2vec and word2vec
- Be able to load models from local tmp directory if they exist
- Added a `RepresentationTrainer` class in `algorithms.occupation_classifiers.train`
- Added/modified several tests for corpus creators and train_occupation_classifiers

Training doc2vec

---

skills_ml/algorithms/aggregators/__init__.py
skills_ml/algorithms/occupation_classifiers/classifiers.py
skills_ml/algorithms/skill_extractors/freetext.py
tests/test_skill_extractors.py
tests/test_title_aggregators.py

- Add OccupationScopedSkillExtractor to create and use an occupation-scoped skill lookup instead of all ONET skills when extracting skills from postings
- Add OccupationScopedSkillAggregator that complies with the expanded interface needed by OccupationScopedSkillExtractor
- Fix usage of FileLock

Occupation-scoped skill extraction [Resolves #95]

---

skills_ml/algorithms/aggregators/field_values.py
tests/test_field_values.py

To support wage extraction, I wanted something to help us analyze just what is in certain fields (or transformations of fields). So I added a FieldValueCounter that I want us to be able to run at will, without necessarily incorporating into Airflow. Here's a simple usage example:
```
from skills_ml.algorithms.aggregators.field_values import FieldValueCounter
from skills_ml.datasets.job_postings import job_postings_highmem
from airflow.hooks import S3Hook
import json
from config import config
conn = S3Hook().get_conn()
job_postings_generator = job_postings_highmem(s3_conn, '2011Q1', config['job_postings']['s3_path'])
counter = FieldValueCounter('2011Q1', ['title'])
extracted_postings = [json.loads(jp) for jp in job_postings_generator]
for posting in extracted_postings: …
```

Count field values

---

skills_ml/algorithms/geocoders/__init__.py
skills_ml/algorithms/job_geography_queriers/cbsa_from_geocode.py
tests/test_geocoders.py
tests/test_job_geo_queriers.py

- Change job_posting_search_string to job_posting_search_strings and return both the city/state and city/statecode versions
- Geocode and cache all job_posting_search_strings for a job posting
- When finding CBSAs, pick the first job_posting_search_string that matches any CBSA
- Show full traceback when quitting geocoding to help debugging
- When loading geocoder, explicitly handle None case and convert to empty dict

Geocode both with state name and code [Resolves #100]

---

examples/Creating Corpus and Sampled Corpus.ipynb
skills_ml/job_postings/common_schema.py
skills_ml/job_postings/corpora/basic.py
skills_ml/job_postings/filtering.py
tests/job_postings/test_filtering.py

The CorpusCreator had gotten too big, and the filtering functionality had to go. Introducing skills_ml.job_postings.filtering, which implements this functionality. The JobPostingFilterer both takes in and produces a generator of JobPostings, so it can be used wherever a JobPostingGenerator can be used.

Move filtering from CorpusCreator to JobPostingFilterer

---

docs/pydocmd.yml
requirements.txt
skills_ml/evaluation/annotators.py
tests/evaluation/test_annotators.py

Functionality to manage a BRAT experiment using a named job posting sample.
Adds a new class, called BratExperiment. This is meant to encompass the following management tasks:
- Creating empty annotation files for all job postings in the sample, in the format that BRAT can read
- Dividing up job postings into allocations based on configuration
- Adding new users and initial allocations
- Adding new allocations to existing users
- Storing all relevant metadata on s3
- Parsing the results of user annotations into labels
This pull request just implements the tasks around the starting and management of experiments. The tasks around parsing the results are deferred to be implemented in a future pull request.
It is not meant to cover the installation of BRAT, or any other devops/infrastructure …

BRAT Experiment [Resolves #136]

---

MANIFEST.in
circle.yml
skills_ml/algorithms/embedding/models.py
skills_ml/algorithms/embedding/train.py
skills_ml/algorithms/occupation_classifiers/classifiers.py
skills_ml/job_postings/computed_properties/computers.py
tests/algorithms/test_occupation_classifiers.py
tests/algorithms/test_train_embedding.py
tests/job_postings/test_computed_properties.py

- Removed s3 dependency from occupation dependency. Now skill-ml should be free from s3 dependency. 
- Add `SocClassifier` as an interface for `SOCClassifyProperty` or other `computers` classes to use.
- `KNNDoc2VecClassifier` is a simple KNN classifier by directly querying from training doc vectors. Ones can feed it's own indexer or call `build_ann_indexer()` which will build a Approximate Nearest Neighbor index (https://github.com/spotify/annoy). Noted that the indexer won't be saved when we call `KNNDoc2VecClassifier().save()`. Only the object itself will be saved. So we might want to build the ann index every time we load the classifier.

Refactoring Occupation Classifier

---

.travis.yml
docs/pydocmd.yml
docs/sources/ontologies.md
skills_ml/datasets/onet_cache.py
skills_ml/datasets/onet_source.py
skills_ml/ontologies/__init__.py
skills_ml/ontologies/base.py
skills_ml/ontologies/onet.py
skills_ml/storage/__init__.py
tests/ontologies/test_base.py

This commit introduces the CompetencyOntology class, which covers competencies and the occupations that they are associated with. ONET is provided as  a sample ontology.
- Add skills_ml.ontologies with base class and ONET
- Refactor ONET dataset source modules so that it is easier to use without dependencies
- Add documentation page about ontology class
- Add InMemoryStore to make ONET more usable upfront

CompetencyOntology and related classes [Resolves #186]

---

docs/pydocmd.yml
docs/sources/ontologies.md
examples/ComputeAndAggregateJobPostingPropertiesLocal.py
examples/UploadCandidatesFromSample.py
skills_ml/algorithms/skill_extractors/base.py
skills_ml/algorithms/skill_extractors/exact_match.py
skills_ml/algorithms/skill_extractors/fuzzy_match.py
skills_ml/algorithms/skill_extractors/soc_exact.py
skills_ml/ontologies/__init__.py
skills_ml/ontologies/base.py
skills_ml/ontologies/onet.py
tests/algorithms/skill_extractors/__init__.py
tests/algorithms/skill_extractors/test_exact_match.py
tests/algorithms/skill_extractors/test_fuzzy_match.py
tests/algorithms/skill_extractors/test_soc_exact.py
tests/job_postings/test_computed_properties.py
tests/ontologies/test_base.py
tests/utils.py

- Add CompetencyFramework to CompetencyOntology to encapsulate just the competency part along with metadata
- Modify all list-based skill extractors to take either a CompetencyFramework or CompetencyOntology
- Update documentation and examples to include new functionality

Apply Ontology to Skill Extraction [Resolves #198]

---

skills_ml/job_postings/computed_properties/computers.py
tests/job_postings/test_computed_properties.py

1. Turns out we needed the statistics import for the mean call
2. Test didn't catch it because it only comes up if we have both min and max value for a wage, hence we needed a test that had both
3. statistics.mode broke in the test where there wasn't a distinct mode, I was going to replace it with the n_most_cmmon that we use for skills and SOC codes but honestly I don't think mode makes sense for this continuous data so I just took it out as a whitelisted metric.

More wage fixes

---

skills_ml/ontologies/base.py
skills_ml/ontologies/onet.py
tests/ontologies/test_base.py

Adds a print_summary_stats() method to the ontology class. In the
printing of these summary stats on ONET, some oddities were found with both the base class and the ONET loader that have been fixed here.
- Ontology name was not included in the serialized version, so if you
wrote and then loaded one it would lose the name
- ONET loader was being too permissive with regards to competency-occupation
edges. It was adding an edge for each line in the file (IM and LV),
which not only duplicated edges but also would add irrelevant edges
along with relevant ones. So instead, the loader only adds
competency-occupation edges from the IM (importance) row, and only if the importance
level is 3 or above. How was this arrived at? ONET's guidelines on the
site. Competencies are only rated as 'important' …

Print Ontology Stats

---

skills_ml/algorithms/skill_extractors/base.py
skills_ml/algorithms/skill_extractors/exact_match.py
skills_ml/algorithms/skill_extractors/fuzzy_match.py
skills_ml/algorithms/skill_extractors/noun_phrase_ending.py
skills_ml/evaluation/annotators.py
skills_ml/evaluation/skill_extraction_metrics.py
skills_ml/storage/__init__.py
tests/algorithms/skill_extractors/test_exact_match.py
tests/evaluation/test_annotators.py
tests/evaluation/test_skill_extraction_metrics.py
tests/utils.py

Adding support for evaluation of a skill extractor's output (as in, a
set of Candidate Skills) against an evaluation set, with basic precision
and recall metrics.
The evaluation set is generally understood to be a gold standard human labeled set, from an
annotation tool such as BRAT. However, it's not limited to this: You can
use this to compare any two lists of CandidateSkills: Two
automatically generated sets, two human labeled sets, or use an
automatically generated one to evaluate a human labeled one.
To make this useful, bindings are introduced to the BratExperiment
object to output CandidateSkills. This replaces the
labels_with_agreement method that was very similar in scope to
CandidateSkills, but so far unused.
To enable this change, the start_index was introduced to the …

Evaluate CandidateSkills against another set [Resolves #218]

---

docs/sources/ontologies.md
skills_ml/ontologies/from_candidate_skills.py
tests/ontologies/test_from_candidate_skills.py

Depending on the method of producing candidate skills, it may be
desirable to create a CompetencyOntology from the candidate skills for
further analysis. Some use cases:
1. the method of producing candidate skills
may produce a very high signal vocabulary with low recall that is a
candidate for more standard exact matching.
2. Comparing this ontology with pre-defined ontologies
- Add ontology_from_candidate_skills which creates a CompetencyOntology from a
list of candidate skills

Create CompetencyOntology from CandidateSkills [Resolves #148]

---

skills_ml/algorithms/string_cleaners/nlp.py
tests/algorithms/test_string_cleaners.py

In running the section extract skill extractor at scale, a couple of
problems were noticed:
- The encoding exception catch block in sentence_tokenize is always hit
- Empty strings break it entirely
Further experimenting with the encoding reveals that
nltk.sentence_tokenize seems to need a string, so I don't think we
should try and encode it at all.
Also, the section_extract had some oddities: it didn't remove any
bullets from returned sections. This is a very minor problem but
removing the bullets does improve the readability of the results
Fixes:
- Add empty document check for section_extract
- Remove encoding block in sentence_tokenize
- Remove bullets from section_extract output
- Remove commented out code in section extract test

Section Extract Fixes

---

docs/sources/ontologies.md
skills_ml/ontologies/__init__.py
skills_ml/ontologies/base.py
skills_ml/ontologies/esco.py
skills_ml/ontologies/onet.py
tests/ontologies/test_base.py

- Add URL, Research Hub options for instantiating ontology. Rearrange
existing options so the constructor isn't too complex
- Add save option to Ontology to make it easier to save/publish
ontologies once they are built
- Finish up ESCO documentation on site

Improve Export/Import of Ontology [Resolves #232]

---

docs/pydocmd.yml
requirements.txt
skills_ml/algorithms/embedding/train.py
skills_ml/job_postings/common_schema.py
skills_ml/utils/__init__.py
tests/algorithms/test_embedding_models.py
tests/algorithms/test_occupation_classifier_tester.py
tests/algorithms/test_occupation_classifiers.py
tests/algorithms/test_train_embedding.py
tests/algorithms/test_train_occupation_classifiers.py
tests/job_postings/test_common_schema.py
tests/test_skill_feature_creator.py

- `EmbeddingTrainer` 
- now is able to train multiple models with the same corpus in multiprocessing way.
- change the interface of the class. the `corpus_generator` should be provided in the `train` method arguments. 
- `BatchGenerator` provide the same functionality of `batches_generator` but can be serialized.

Multiprocessing embedding

---

skills_ml/algorithms/preprocessing/__init__.py

The `if` statement here is to prevent the generator from yielding `None`. The way it was implemented will still yield `None` if the `func(item)` is None.

Fixed IterablePipeline for yielding None
